---
- name: Create comparment for DNS Services
  vars_files:
    - vars.yml
    - secrets.yml
  connection: local
  hosts: localhost
  tasks:
    - name: Gather all compartments facts
      oracle.oci.oci_identity_compartment_facts:
        parent_compartment_id: "{{ root_compartment }}"
    - name: Create compartment for DNS Services
      oracle.oci.oci_identity_compartment:
        description: "DNSServices"
        name: DNSServices
        parent_compartment_id: "{{ root_compartment }}"
        region: "{{ def_region }}"
        state: present
        wait: yes
      register: result
    - set_fact: dnsservices_compartment={{ result.compartment.id }}
    - name: Dump debug information
      debug:
        msg: "New DNSServices compartment ID: {{dnsservices_compartment}}"

