---
- name: Create comparment for DNS services
  vars_files:
    - vars.yml
    - secrets.yml
  connection: local
  hosts: localhost
  tasks:
    - name: Create compartment
      oracle.oci.oci_identity_compartment:
        description: "DNS services"
        name: DNS_services
        parent_compartment_id: "{{ root_compartment }}"
        region: "{{ dns_region }}"
        state: present
        wait: yes
      register: result
    - set_fact: dns_compartment={{ result.compartment.compartment_id }}
    - name: Dump debug information
      debug:
        msg: "New DNS compartment ID: {{dns_compartment}}"

