---
- name : Get inventory file stat
  connection: local
  hosts: localhost
  tasks:
    - name: Get stat of a file
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/tmp/oci-cache/oci_oracle.oci.oci_00b36s_11f65"
      register: stat_result
    - name: Dump results - mtime
      debug:
        msg: '{{stat_result.stat.mtime}}'
- name : Refresh OCI inventory
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: Refresh inventory
      meta: refresh_inventory
- name : Get inventory file stat
  connection: local
  hosts: localhost
  tasks:
    - name: Get stat of a file
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/tmp/oci-cache/oci_oracle.oci.oci_00b36s_11f65"
      register: stat_result
    - name: Dump results - mtime
      debug:
        msg: '{{stat_result.stat.mtime}}'

